### ISSUE TITLE
Linux version throw core error and can't connect to the pozyx tag.

### ISSUE THREAD

**Issue by goldarte** [pozyxLabs/Creator-Controller-Software#1]
**The bug description**
When I execute pozyx-creator-controller appimage file, I get next errors:

```bash
./pozyx-creator-controller-2.0.0.appimage 
```
16:26:19.491 › Running production build
16:26:19.908 › Started connector software.
16:26:19.952 › Core not running externally, starting packaged core.
16:26:19.953 › Starting pozyx core from /tmp/.mount_pozyx-yX2NUX/resources/bin/core-creator
16:26:19.958 › Started pozyx core
16:26:19.958 › Error starting core TypeError: Cannot read property 'on' of undefined
16:26:19.959 › Core error, code Error: spawn /tmp/.mount_pozyx-yX2NUX/resources/bin/core-creator EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
16:26:19.960 › Core closed, code: -13
16:26:19.960 › Cloud connector not running externally, starting packaged cloud connector.
16:26:19.961 › Starting cloud connector from /tmp/.mount_pozyx-yX2NUX/resources/bin/gateway-api

The program shell is running, but I can't connect to any device. I'm using working cable and tag: I can change its settings with device configurator 2.0.0.
My user is in dialout group and has necessary rights to connect to serial ports.
I'm using Ubuntu 16.04.

**Expected behavior**
Normally executing program without errors

**Version**
2.0.0

Available logs are attached:

[controller_log.txt](https://github.com/pozyxLabs/Creator-Controller-Software/files/3456967/controller_log.txt)

[cloud_connector_log.txt](https://github.com/pozyxLabs/Creator-Controller-Software/files/3456963/cloud_connector_log.txt)

**Comment by goldarte** [comment]
Thanks for the prompt solution of the problem! Now I can connect tag to creator controller and do calibration or visualize the position of the tag.

**Comment by laurentva** [comment]
Hey Arthur,

Glad to see that fixed it! Thanks for closing the issue :).
